name: Zip Files

on:
  #release: #that would be if attaining to releases
  #  types: [published]
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.1
        with:
          files: plugin.video.lo-scienziato-pazzo
          dest: repo/installer.zip